# Generated by Django 4.2.30 on 2026-06-24 18:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0002_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=tinymce.models.HTMLField(),
        ),
    ]
