# Generated by Django 4.2.30 on 2026-06-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0003_alter_artigo_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='id_fk_autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='artigo',
            old_name='id_fk_eixo',
            new_name='eixo',
        ),
    ]
