# Generated by Django 4.2.30 on 2026-06-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0004_rename_id_fk_autor_artigo_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
